# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        exclude_types: [ jupyter ]
      - id: end-of-file-fixer
        exclude_types: [ jupyter ]
      - id: check-docstring-first
      - id: debug-statements
      - id: check-ast
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    # Ruff version.
    rev: v0.0.246
    hooks:
      - id: ruff
        # Respect `exclude` and `extend-exclude` settings.
        args: [ --fix,
                --line-length, "120",
                --target-version, "py310",
        ]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.0.0
    hooks:
      - id: mypy
        args: [ --python-version=3.10,
                --disallow-untyped-calls,
                --disallow-untyped-defs,
                --disallow-incomplete-defs,
                --check-untyped-defs,
                --no-implicit-optional,
                --warn-redundant-casts,
                --ignore-missing-imports,
        ]
        exclude_types: [ jupyter ]
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        args: [ --profile=black,
                --line-length=120,
                --multi-line=VERTICAL_HANGING_INDENT,
                --length-sort,
                --trailing-comma,
                --force-grid-wrap=0,
                --use-parentheses
        ]
